### ISSUE TITLE
Debug build crashes

### ISSUE THREAD

**Issue by chrisseaton** [mmtk/mmtk-ruby#17] opened 2022-10-02 21:23 UTC
https://github.com/Shopify/ruby-mmtk-builder/actions/runs/3166668970/jobs/5156533811#step:3:4277

```
+ ruby/build/bin/ruby --mmtk -v
~/work/ruby-mmtk-builder/ruby-mmtk-builder
[2022-10-02T00:15:59Z INFO  mmtk::memory_manager] Initialized MMTk with MarkSweep
thread '<unnamed>' panicked at 'assertion failed: start + bytes <= space_start + MAX_SPACE_EXTENT', /home/runner/work/ruby-mmtk-builder/ruby-mmtk-builder/mmtk-core/src/policy/sft_map.rs:151:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
./build.sh: line 57: 18574 Aborted                 (core dumped) ruby/build/bin/ruby --mmtk -v
```

Suddenly started failing a few days ago.

**Comment by qinsoon** [comment] 2022-10-02 23:04
I think it is related to the changes in https://github.com/mmtk/mmtk-core/pull/632, which aimed to mitigate the issue https://github.com/mmtk/mmtk-ruby/issues/13. To use the current mark sweep plan, you would need to enable [the `malloc_mark_sweep` feature](https://github.com/mmtk/mmtk-core/blob/f82848847a6392537fec6b914d7ad95fbf28b0a2/Cargo.toml#L121) (something like `default = ["mmtk/malloc_mark_sweep"]`).

We will soon have a proper mark sweep plan, and at that point, you don't need to use `malloc_mark_sweep`.

**Comment by wks** [comment] 2022-10-11 08:51
I couldn't reproduce this problem locally even with debug build.  But I added "malloc_mark_sweep" feature to the `mmtk` dependency in https://github.com/mmtk/mmtk-ruby/commit/ffdb9dc660875c2405fb9158c0c3f1e219d2b0ee

Let's see how it runs on the nightly build server.

**Comment by wks** [comment] 2022-10-13 06:33
It now builds normally since this run: https://github.com/Shopify/ruby-mmtk-builder/actions/runs/3231076400

I am closing this issue.

**Closed by wks** 2022-10-13 06:33 UTC
